apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  namespace: default
  labels:
    app: java-app
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
      annotations:
        test: test
    spec:
      containers:
        - image: mcr.microsoft.com/dotnet/samples:aspnetapp
          name: java-app
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              cpu: '2'
              memory: 1024M
