apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namespace: default
  labels:
    app: nodejs-app
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
      annotations:
        test: test
    spec:
      containers:
        - image: mcr.microsoft.com/dotnet/samples:aspnetapp
          name: nodejs-app
          ports:
            - containerPort: 80
              name: http
          # resources:
          #   limits:
          #     cpu: '2'
          #     memory: 1024M
