apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
  namespace: default
  labels:
    app: php-app
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
      annotations:
        test: test
    spec:
      containers:
        - image: bkimminich/juice-shop:v14.0.0
          name: php-app
          ports:
            - containerPort: 80
              name: http
          # resources:
          #   limits:
          #     cpu: '2'
          #     memory: 1024M
