apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: contrast-agent-operator
  namespace: contrast-agent-operator
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: operator
      app.kubernetes.io/part-of: contrast-agent-operator
