apiVersion: v1
kind: Service
metadata:
  name: contrast-agent-operator
  namespace: contrast-agent-operator
spec:
  ports:
    - name: https
      port: 443
      targetPort: 5001
  selector:
    app: contrast-agent-operator
