apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: contrast-web-hook-configuration
webhooks:
  - name: pods.agents.contrastsecurity.com
    reinvocationPolicy: IfNeeded
    failurePolicy: Ignore
    timeoutSeconds: 2
    rules:
      - apiGroups: [ "" ]
        apiVersions: [ "v1" ]
        operations: [ "CREATE" ]
        resources: [ "pods" ]
        scope: Namespaced
    clientConfig:
      service:
        name: contrast-agent-operator
        namespace: contrast-agent-operator
        path: /v1/pods/podcontroller/mutate
    admissionReviewVersions: [ "v1" ]
    sideEffects: None
