apiVersion: agents.contrastsecurity.com/v1beta1
kind: AgentConnection
metadata:
  name: testing-agent-connection
spec:
  url: http://localhost
  apiKey:
    secretName: testing-agent-connection-secret
    secretKey: apiKey
  serviceKey:
    secretName: testing-agent-connection-secret
    secretKey: serviceKey
  userName:
    secretName: testing-agent-connection-secret
    secretKey: userName
---
apiVersion: v1
kind: Secret
metadata:
  name: testing-agent-connection-secret
type: Opaque
stringData:
  apiKey: apiKey
  serviceKey: serviceKey
  userName: userName
---
apiVersion: agents.contrastsecurity.com/v1beta1
kind: AgentConfiguration
metadata:
  name: testing-agent-configuration
spec:
  yaml: |
    enabled: false
    foo:
      bar: "foobar"
    test:
      namespace: "%namespace%"
      label: "%labels.test-label%"
      annotation: "%annotations.test-annotation%"
      container_image: "%container.dotnet-test.image%"
      multiple: "%namespace%_%namespace%"
  enableYamlVariableReplacement: true
