apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: contrast-agent-operator-service-role
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/part-of: contrast-agent-operator
rules:
- apiGroups:
  - ""
  - apps
  - apps.openshift.io
  - agents.contrastsecurity.com
  resources:
  - pods
  - statefulsets
  - deploymentconfigs
  - agentconnections
  - agentconfigurations
  - agentinjectors
  - daemonsets
  - deployments
  verbs:
  - get
  - list
  - watch
  - patch
- apiGroups:
  - ""
  - coordination.k8s.io
  resources:
  - secrets
  - leases
  verbs:
  - '*'
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - create
  - get
  - list
  - watch
  - patch
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - ""
  - admissionregistration.k8s.io
  resources:
  - services
  - validatingwebhookconfigurations
  verbs:
  - create
  - get
  - patch
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - statefulsets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - daemonsets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - services/status
  verbs:
  - get
  - patch
  - update
