apiVersion: apps/v1
kind: DeploymentConfig
metadata:
  name: dotnet-core-app
  namespace: default
  labels:
    app: dotnet-core-app
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: dotnet-core-app
  template:
    metadata:
      labels:
        app: dotnet-core-app
      annotations:
        test: test
    spec:
      containers:
        - image: mcr.microsoft.com/dotnet/samples:aspnetapp
          name: dotnet-core-app
          ports:
            - containerPort: 80
              name: http
