apiVersion: v1
kind: Service
metadata:
  name: asp-net-core
  namespace: default
  labels:
    app: asp-net-core
spec:
  ports:
    - name: http
      port: 80
  selector:
    app: asp-net-core
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: asp-net-core
  namespace: default
  labels:
    app: asp-net-core
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: asp-net-core
  template:
    metadata:
      labels:
        app: asp-net-core
      annotations:
        test: test
    spec:
      containers:
        - image: mcr.microsoft.com/dotnet/samples:aspnetapp
          name: asp-net-core
          ports:
            - containerPort: 80
              name: http
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
---
