apiVersion: agents.contrastsecurity.com/v1beta1
kind: AgentInjector
metadata:
  name: example-injector-dotnet-core
spec:
  enabled: true
  version: latest
  type: dotnet-core
  selector:
    images:
      - "*"
    labels:
      - name: app
        value: dotnet-core-app
  connection:
    name: example-agent-connection
  configuration:
    name: example-agent-configuration
---
apiVersion: agents.contrastsecurity.com/v1beta1
kind: AgentInjector
metadata:
  name: example-injector-dotnet-core-chaining
spec:
  enabled: true
  version: latest
  type: dotnet-core
  selector:
    images:
      - "*"
    labels:
      - name: app
        value: dotnet-core-chaining-app
  connection:
    name: example-agent-connection
  configuration:
    name: example-agent-configuration
---
apiVersion: agents.contrastsecurity.com/v1beta1
kind: AgentInjector
metadata:
  name: example-injector-java
spec:
  enabled: true
  version: latest
  type: java
  selector:
    images:
      - "*"
    labels:
      - name: app
        value: java-app
  connection:
    name: example-agent-connection
  configuration:
    name: example-agent-configuration
---
apiVersion: agents.contrastsecurity.com/v1beta1
kind: AgentInjector
metadata:
  name: example-injector-nodejs
spec:
  enabled: true
  version: latest
  type: nodejs
  selector:
    images:
      - "*"
    labels:
      - name: app
        value: nodejs-app
  connection:
    name: example-agent-connection
  configuration:
    name: example-agent-configuration
---
apiVersion: agents.contrastsecurity.com/v1beta1
kind: AgentInjector
metadata:
  name: example-injector-php
spec:
  enabled: true
  version: latest
  type: php
  selector:
    images:
      - "*"
    labels:
      - name: app
        value: php-app
  connection:
    name: example-agent-connection
  configuration:
    name: example-agent-configuration
---
apiVersion: agents.contrastsecurity.com/v1beta1
kind: AgentConnection
metadata:
  name: example-agent-connection
spec:
  url: http://localhost
  apiKey:
    secretName: example-agent-connection-secret
    secretKey: apiKey
  serviceKey:
    secretName: example-agent-connection-secret
    secretKey: serviceKey
  userName:
    secretName: example-agent-connection-secret
    secretKey: userName
---
apiVersion: v1
kind: Secret
metadata:
  name: example-agent-connection-secret
type: Opaque
stringData:
  apiKey: apiKey
  serviceKey: serviceKey
  userName: userName
---
apiVersion: agents.contrastsecurity.com/v1beta1
kind: AgentConfiguration
metadata:
  name: example-agent-configuration
spec:
  yaml: |
    enabled: true
