apiVersion: v1
kind: ServiceAccount
metadata:
  name: contrast-agent-operator-service-account
  namespace: contrast-agent-operator
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/part-of: contrast-agent-operator
