apiVersion: v1
kind: Secret
metadata:
  name: cluster-agent-connection-secret
  namespace: testing-agent-operator
type: Opaque
stringData:
  token: token
  apiKey: apiKey
  serviceKey: serviceKey
  userName: userName
