apiVersion: v1
kind: Secret
metadata:
  name: cluster-image-pullsecret
  namespace: testing-agent-operator
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyIiOnsidXNlcm5hbWUiOiIiLCJwYXNzd29yZCI6IiIsImVtYWlsIjoiIiwiYXV0aCI6IiJ9fX0=
