apiVersion: agents.contrastsecurity.com/v1beta1
kind: AgentInjector
metadata:
  name: injection-php
spec:
  enabled: true
  type: php
  selector:
    labels:
      - name: app
        value: injection-php
  image:
    pullPolicy: Never
  connection:
    name: testing-agent-connection
  configuration:
    name: testing-agent-configuration
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: injection-php
  labels:
    app: injection-php
spec:
  replicas: 1
  selector:
    matchLabels:
      app: injection-php
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: injection-php
    spec:
      containers:
        - image: busybox
          imagePullPolicy: Never
          name: busybox
          resources:
            limits:
              cpu: '1'
              memory: 128M
