apiVersion: agents.contrastsecurity.com/v1beta1
kind: AgentInjector
metadata:
  name: injection-dotnet
spec:
  enabled: true
  type: dotnet-core
  selector:
    labels:
      - name: app
        value: injection-dotnet
  image:
    pullPolicy: Never
  connection:
    name: testing-agent-connection
  configuration:
    name: testing-agent-configuration
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: injection-dotnet
  labels:
    app: injection-dotnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: injection-dotnet
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: injection-dotnet
    spec:
      containers:
        - image: busybox
          imagePullPolicy: Never
          name: busybox
          resources:
            limits:
              cpu: '1'
              memory: 128M
