apiVersion: apps/v1
kind: Deployment
metadata:
  name: contrast-agent-operator
  namespace: contrast-agent-operator
spec:
  replicas: 1
  template:
    spec:
      imagePullSecrets:
       - name: contrastdotnet-pull-secret
      containers:
        - name: contrast-agent-operator
          env:
            - name: CONTRAST_DEFAULT_REGISTRY
              value: contrastdotnet.azurecr.io/agent-operator
