apiVersion: apps/v1
kind: Deployment
metadata:
  name: contrast-agent-operator
  namespace: contrast-agent-operator
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: contrast-agent-operator
          imagePullPolicy: Never
          env:
            - name: CONTRAST_AGENT_TELEMETRY_OPTOUT
              value: "true"
            - name: "CONTRAST_LOG_LEVEL"
              value: "TRACE"
