bases:
  - rbac

resources:
  - crd/agentconfigurations_agents_contrastsecurity_com.yaml
  - crd/agentconnections_agents_contrastsecurity_com.yaml
  - crd/agentinjectors_agents_contrastsecurity_com.yaml
