clusterDefaults:
  enabled: true
  url: https://app-agents.contrastsecurity.com/Contrast
  apiKeyValue: testing
  serviceKeyValue: testing
  userNameValue: testing
  yaml: |-
    enable: true
    second-line: something

image:
  registry: contrast
  repository: agent-operator
  tag:

agentInjectors:
  enabled: true
  useClusterAgentInjectors: true
  namespaces:
    - test1
    - test2
  namespaceLabelSelector:
    - name: agents.contrastsecurity.com/agent-injectors
      value: 'true'
  injectors:
    - language: java
      name: helm-java-injector
      selector:
        labels:
          - name: contrast-agent
            value: java
