clusterDefaults:
  enabled: true
  url: https://app-agents.contrastsecurity.com/Contrast
  apiKeyValue: testing
  serviceKeyValue: testing
  userNameValue: testing
  yaml: |-
    enable: true
    second-line: something

namespace: contrast-agent-operator
image:
  registry: contrast
  repository: agent-operator
  tag: latest

agentInjectors:
  enabled: true
  namespaces:
    - test1
    - test2
  injectors:
    - language: java
      name: helm-java-injector
      selector:
        labels:
          - name: contrast-agent
            value: java
