apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-dotnet-core
  namespace: dev
  labels:
    app: cluster-dotnet-core
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: cluster-dotnet-core
  template:
    metadata:
      labels:
        app: cluster-dotnet-core
      annotations:
        test: test
    spec:
      containers:
        - image: contrast/sample-app-aspnetcore:latest
          name: cluster-dotnet-core
          ports:
            - containerPort: 80
              name: http
          livenessProbe:
            httpGet:
              path: /
              port: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
          resources:
            limits:
              cpu: '1'
              memory: 1024M
