apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app
  namespace: dev
  labels:
    app: java-app
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: java-app
  template:
    metadata:
      labels:
        app: java-app
      annotations:
        test: test
    spec:
      containers:
        - image: webgoat/webgoat-8.0:v8.1.0
          name: java-app
          ports:
            - containerPort: 8080
              name: http
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 8080
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 8080
          # resources:
          #   limits:
          #     cpu: '2'
          #     memory: 1024M
