apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
  namespace: dev
  labels:
    app: php-app
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
      annotations:
        test: test
    spec:
      containers:
        - image: contrast/sample-app-php
          name: php-app
          ports:
            - containerPort: 80
              name: http
          env:
            - name: CONTRAST__AGENT__LOGGER__PATH
              value: /tmp/contrast.log
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 80
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 80
          # resources:
          #   limits:
          #     cpu: '2'
          #     memory: 1024M
