apiVersion: agents.contrastsecurity.com/v1beta1
kind: AgentInjector
metadata:
  name: chaining-python
spec:
  enabled: true
  type: python
  selector:
    labels:
      - name: app
        value: chaining-python
  image:
    pullPolicy: Never
  connection:
    name: testing-agent-connection
  configuration:
    name: testing-agent-configuration
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaining-python
  labels:
    app: chaining-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chaining-python
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chaining-python
    spec:
      containers:
        - image: k8s.gcr.io/pause:3.3
          name: pause
          env:
            - name: PYTHONPATH
              value: something
