apiVersion: agents.contrastsecurity.com/v1beta1
kind: AgentInjector
metadata:
  name: enabled-flag
spec:
  enabled: false
  type: dummy
  image:
    pullPolicy: Never
  selector:
    labels:
      - name: app
        value: enabled-flag
  connection:
    name: testing-agent-connection
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: enabled-flag
  labels:
    app: enabled-flag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enabled-flag
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: enabled-flag
    spec:
      containers:
        - image: k8s.gcr.io/pause:3.3
          name: pause
