apiVersion: agents.contrastsecurity.com/v1beta1
kind: AgentInjector
metadata:
  name: injection-javatooloptions
spec:
  enabled: true
  type: java
  selector:
    labels:
      - name: app
        value: injection-javatooloptions
  image:
    pullPolicy: Never
  connection:
    name: testing-agent-connection
  configuration:
    name: testing-agent-configuration
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: injection-javatooloptions
  labels:
    app: injection-javatooloptions
spec:
  replicas: 1
  selector:
    matchLabels:
      app: injection-javatooloptions
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: injection-javatooloptions
    spec:
      containers:
        - image: k8s.gcr.io/pause:3.3
          name: pause
          env:
            - name: JAVA_TOOL_OPTIONS
              value: something
