apiVersion: agents.contrastsecurity.com/v1beta1
kind: AgentInjector
metadata:
  name: unmatched
spec:
  enabled: true
  type: dummy
  image:
    pullPolicy: Never
  selector:
    labels:
      - name: app
        value: unmatched
  connection:
    name: testing-agent-connection
