// Contrast Security, Inc licenses this file to you under the Apache 2.0 License.
// See the LICENSE file in the project root for more information.

using Contrast.K8s.AgentOperator.Core.Kube;
using k8s.Models;
using KubeOps.Abstractions.Entities;
using KubeOps.Abstractions.Entities.Attributes;
using KubeOps.Abstractions.Rbac;

namespace Contrast.K8s.AgentOperator.Entities;

[KubernetesEntity(Group = "agents.contrastsecurity.com", ApiVersion = "v1beta1", Kind = "AgentConfiguration", PluralName = "agentconfigurations")]
[EntityRbac(typeof(V1Beta1AgentConfiguration), Verbs = VerbConstants.All)]
public partial class V1Beta1AgentConfiguration : CustomKubernetesEntity<V1Beta1AgentConfiguration.AgentConfigurationSpec>
{
    public class AgentConfigurationSpec
    {
        [Description("The contrast_security.yaml file. Multiple lines are supported.")]
        public string? Yaml { get; set; }

        [Description("If false, automatically set the Contrast server name on injected workloads ('kubernetes-{namespace}'), rather than use the default (normally the pod name). Defaults to false.")]
        public bool? SuppressDefaultServerName { get; set; }

        [Description("If false, automatically set the Contrast application name on injected workloads (the workload name), rather than use the default (generated by the agent). Defaults to false.")]
        public bool? SuppressDefaultApplicationName { get; set; }

        [Description("If true, parse and replace %variables% in spec.yaml section. Defaults to false.")]
        public bool? EnableYamlVariableReplacement { get; set; }

        [Description("Optional spec to apply to the Contrast InitContainer. If not specified, reasonable defaults are used.")]
        public InitContainerOverridesSpec? InitContainer { get; set; }
    }

    public class InitContainerOverridesSpec
    {
        [Description("SecurityContext defines the security options the container should be run with. If set, the fields of SecurityContext override the equivalent fields of PodSecurityContext.")]
        [ExternalDocs("https://kubernetes.io/docs/tasks/configure-pod-container/security-context/")]
        public V1SecurityContext? SecurityContext { get; set; }
    }
}
