apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: agentinjectors.agents.contrastsecurity.com
  labels:
    app.kubernetes.io/part-of: contrast-agent-operator
spec:
  group: agents.contrastsecurity.com
  names:
    kind: AgentInjector
    listKind: AgentInjectorList
    plural: agentinjectors
    singular: agentinjector
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              enabled:
                description: Enable this agent injector. Defaults to 'true'.
                type: boolean
              version:
                description: The version of the agent to inject. The literal 'latest' will inject the latest version. Partial version matches are supported, e.g. '2' will select the version '2.1.0'. Defaults to 'latest'.
                nullable: true
                pattern: ^(latest|(\d+(\.\d+){0,3}(-.+)?))$
                type: string
              type:
                description: The type of agent to inject. Can be one of ['dotnet-core', 'java', 'nodejs', 'nodejs-legacy', 'php', 'python']. Required.
                pattern: ^(dotnet-core|dotnet|java|node|nodejs|node-esm|nodejs-esm|nodejs-legacy|php|personal-home-page|python|dummy)$
                type: string
              image:
                description: Overrides the default agent images.
                properties:
                  registry:
                    description: The fully qualified name of the registry to pull agent images from. This registry must be accessible by the pods being injected and the operator. Defaults to the official Contrast container image registry.
                    nullable: true
                    type: string
                  name:
                    description: The name of the injector image to use. The default depends on the value of spec.type.
                    nullable: true
                    type: string
                  pullSecretName:
                    description: The name of a pull secret to append to the pod's imagePullSecrets list.
                    nullable: true
                    type: string
                  pullPolicy:
                    description: The pull policy to use when fetching Contrast images. See Kubernetes imagePullPolicy for more information. Defaults to 'Always'.
                    nullable: true
                    pattern: ^(Always|IfNotPresent|Never)$
                    type: string
                type: object
              selector:
                description: Select which Deployment/StatefulSet/DaemonSet/Rollout pods are eligible for agent injection. Under OpenShift, DeploymentConfig is also supported.
                properties:
                  images:
                    description: Container images to inject the agent into. Glob patterns are supported. If empty (the default), selects all containers in Pod.
                    items:
                      type: string
                    type: array
                  labels:
                    description: Deployment/StatefulSet/DaemonSet/DeploymentConfig labels whose pods are eligible for agent injection. If empty (the default), selects all workloads in namespace.
                    items:
                      properties:
                        name:
                          description: The name of the label to match. Required.
                          type: string
                        value:
                          description: The value of the label to match. Glob patterns are supported. Required.
                          type: string
                      required:
                      - name
                      - value
                      type: object
                    type: array
                type: object
              connection:
                description: The connection the injected agent will use to communicate with Contrast.
                nullable: true
                properties:
                  name:
                    description: The name of AgentConnection resource. Must exist within the same namespace. Defaults to the AgentConnection specified by a ClusterAgentConnection.
                    nullable: true
                    type: string
                type: object
              configuration:
                description: The configuration the injected agent will use.
                nullable: true
                properties:
                  name:
                    description: The name of a AgentConfiguration resource. Must exist within the same namespace. Defaults to the AgentConfiguration specified by a ClusterAgentConfiguration.
                    nullable: true
                    type: string
                type: object
            required:
            - type
            type: object
        type: object
    served: true
    storage: true
