apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusteragentconfigurations.agents.contrastsecurity.com
  labels:
    app.kubernetes.io/part-of: contrast-agent-operator
spec:
  group: agents.contrastsecurity.com
  names:
    kind: ClusterAgentConfiguration
    listKind: ClusterAgentConfigurationList
    plural: clusteragentconfigurations
    singular: clusteragentconfiguration
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            description: Specification of the kubernetes object.
            properties:
              template:
                description: |-
                  The default AgentConfiguration to apply to the namespaces selected by 'spec.namespaces'.
                  Required.
                nullable: true
                properties:
                  spec:
                    description: Specification of the kubernetes object.
                    properties:
                      yaml:
                        description: The contrast_security.yaml file. Multiple lines are supported.
                        nullable: true
                        type: string
                      suppressDefaultServerName:
                        description: |-
                          If false, automatically set the Contrast server name on injected workloads ('kubernetes-{namespace}'),
                          rather than use the default (normally the pod name).
                          Defaults to false.
                        nullable: true
                        type: boolean
                      suppressDefaultApplicationName:
                        description: |-
                          If false, automatically set the Contrast application name on injected workloads (the workload name),
                          rather than use the default (generated by the agent).
                          Defaults to false.
                        nullable: true
                        type: boolean
                    type: object
                  metadata:
                    description: The metadata of the kubernetes object.
                    type: object
                  apiVersion:
                    type: string
                  kind:
                    type: string
                type: object
              namespaces:
                description: |-
                  The namespaces to apply this AgentConfiguration template to. Glob syntax is supported.
                  Optional, defaults to selecting all namespaces.
                items:
                  type: string
                type: array
            required:
            - template
            type: object
        type: object
    served: true
    storage: true
