apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clusteragentconnections.agents.contrastsecurity.com
  labels:
    app.kubernetes.io/part-of: contrast-agent-operator
spec:
  group: agents.contrastsecurity.com
  names:
    kind: ClusterAgentConnection
    listKind: ClusterAgentConnectionList
    plural: clusteragentconnections
    singular: clusteragentconnection
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              template:
                description: The default AgentConnection to apply to the namespaces selected by 'spec.namespaces'. Required.
                nullable: true
                properties:
                  spec:
                    properties:
                      mountAsVolume:
                        description: If true, mount the AgentConnection secrets as a volume. Defaults to false. This will override CONTRAST_CONFIG_PATH on the pod.
                        nullable: true
                        type: boolean
                      token:
                        description: The Token to use for this connection.
                        nullable: true
                        properties:
                          secretName:
                            description: The name of the secret to reference. Must exist in the same namespace as the AgentConnection. Required.
                            type: string
                          secretKey:
                            description: The key in the secret to access the value for. Must exist in the same namespace as the AgentConnection. Required.
                            type: string
                        required:
                        - secretName
                        - secretKey
                        type: object
                      url:
                        description: The URL of the Contrast server. Defaults to 'https://app-agents.contrastsecurity.com/Contrast'.
                        nullable: true
                        type: string
                      apiKey:
                        description: The API Key to use for this connection.
                        nullable: true
                        properties:
                          secretName:
                            description: The name of the secret to reference. Must exist in the same namespace as the AgentConnection. Required.
                            type: string
                          secretKey:
                            description: The key in the secret to access the value for. Must exist in the same namespace as the AgentConnection. Required.
                            type: string
                        required:
                        - secretName
                        - secretKey
                        type: object
                      serviceKey:
                        description: The ServiceKey to use for this connection.
                        nullable: true
                        properties:
                          secretName:
                            description: The name of the secret to reference. Must exist in the same namespace as the AgentConnection. Required.
                            type: string
                          secretKey:
                            description: The key in the secret to access the value for. Must exist in the same namespace as the AgentConnection. Required.
                            type: string
                        required:
                        - secretName
                        - secretKey
                        type: object
                      userName:
                        description: The UserName to use for this connection.
                        nullable: true
                        properties:
                          secretName:
                            description: The name of the secret to reference. Must exist in the same namespace as the AgentConnection. Required.
                            type: string
                          secretKey:
                            description: The key in the secret to access the value for. Must exist in the same namespace as the AgentConnection. Required.
                            type: string
                        required:
                        - secretName
                        - secretKey
                        type: object
                    type: object
                  metadata:
                    type: object
                  apiVersion:
                    type: string
                  kind:
                    type: string
                type: object
              namespaces:
                description: The namespaces to apply this AgentConnection template to. Glob syntax is supported. Optional, defaults to selecting all namespaces.
                items:
                  type: string
                type: array
            required:
            - template
            type: object
        type: object
    served: true
    storage: true