apiVersion: agents.contrastsecurity.com/v1beta1
kind: AgentInjector
metadata:
  name: injection-java
spec:
  enabled: true
  type: java
  selector:
    labels:
      - name: app
        value: injection-java
  image:
    pullPolicy: Never
  connection:
    name: testing-agent-connection
  configuration:
    name: testing-agent-configuration
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: injection-java
  labels:
    app: injection-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: injection-java
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: injection-java
    spec:
      containers:
        - image: k8s.gcr.io/pause:3.3
          name: pause
