apiVersion: agents.contrastsecurity.com/v1beta1
kind: AgentInjector
metadata:
  name: multiple-images
spec:
  enabled: true
  type: dummy
  selector:
    images:
      - busybox:stable
    labels:
      - name: app
        value: multiple-images
  image:
    pullPolicy: Never
  connection:
    name: testing-agent-connection
  configuration:
    name: testing-agent-configuration
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: multiple-images
  labels:
    app: multiple-images
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multiple-images
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: multiple-images
    spec:
      containers:
        - image: busybox:stable
          name: busybox
          command: [ "/bin/sh", "-c", "--" ]
          args: [ "sleep infinity" ]
        - image: k8s.gcr.io/pause:3.3
          name: pause
