bases:
  - ../prod

images:
  - name: contrastsecurity.com/agent-operator/operator
    newName: contrastdotnet.azurecr.io/agent-operator/operator
    newTag: master

patchesStrategicMerge:
  - overlays/deployment.yaml
