bases:
  - ../prod

images:
  - name: contrast/agent-operator
    newName: contrastdotnet.azurecr.io/agent-operator/agent-operator
    newTag: latest

patchesStrategicMerge:
  - overlays/deployment.yaml
