namespace: testing-agent-operator

bases:
  - ../all

images:
  - name: contrastsecurity.com/agent-operator/operator
    newName: local/agent-operator
    newTag: latest

patchesStrategicMerge:
  - overlays/deployment.yaml
