namespace: testing-agent-operator

resources:
  - ../all

images:
  - name: contrast/agent-operator
    newName: local/agent-operator
    newTag: latest

patchesStrategicMerge:
  - overlays/deployment.yaml
