name: Wiz Scan
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_call:

permissions:
  contents: read

jobs:
  wiz-scan:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      POLICY: "Contrast-OSS,EOL-Scan"
      WIZ_CLI_VERSION: "1.50.0"
    permissions:
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Build the Docker image
        run: docker build . --tag agent-operator:dev

      - name: Download Wiz CLI
        run: curl -fsSLo wizcli https://downloads.wiz.io/v1/wizcli/${WIZ_CLI_VERSION}/wizcli-linux-amd64 && chmod +x wizcli

      - name: Run Wiz CLI container image scan
        run: ./wizcli scan container-image agent-operator:dev --client-id "$WIZ_CLIENT_ID" --client-secret "$WIZ_CLIENT_SECRET" --assist-migration --policies "$POLICY" --csv-output-file="agent-operator-wiz-report.zip" --by-policy-hits="BLOCK" --show-ignored-by-grace-period
        env:
          WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
          WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}

      - name: Capture Wiz Output
        if: always()
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: agent-operator-wiz-report
          path: |
            agent-operator-wiz-report.zip
          retention-days: 7
